vim.keymap.set("n", "<leader>xx", ':TroubleToggle<CR>', { desc = 'Trouble: Open' })
vim.keymap.set("n", "<leader>xw", function() require("trouble").open("workspace_diagnostics") end, { desc = 'Trouble: [W]orkspace Diagnositcs' })
vim.keymap.set("n", "<leader>xd", function() require("trouble").open("document_diagnostics") end, { desc = 'Trouble: [D]ocument Diagnostics' })
vim.keymap.set("n", "<leader>xq", function() require("trouble").open("quickfix") end, { desc = 'Trouble: [Q]uickfix Menu' })
vim.keymap.set("n", "<leader>xl", function() require("trouble").open("loclist") end, { desc = 'Trouble: [L]ocation List' })
