return {
    "stevearc/aerial.nvim",
    event = { "BufReadPost", "BufWritePost", "BufNewFile" },
    keys = {
        { "<leader>at", "<cmd>AerialToggle<cr>", desc = "[A]erial [T]oggle" },
    },
    config = function ()
        local aerial = require('aerial')
        aerial.setup({
            attach_mode = "global",
            backends = { "lsp", "treesitter", "markdown", "man" },
            close_on_select = true,
            layout = {
                resize_to_content = false,
            },
            icons = {
                Array         = " ",
                Boolean       = "󰨙 ",
                Class         = " ",
                Codeium       = "󰘦 ",
                Collapsed     = " ",
                Color         = " ",
                Constant      = " ",
                Constructor   = " ",
                Control       = " ",
                Copilot       = " ",
                Enum          = " ",
                EnumMember    = " ",
                Event         = " ",
                Field         = " ",
                File          = " ",
                Folder        = " ",
                Function      = " ",
                Interface     = " ",
                Key           = " ",
                Keyword       = " ",
                Method        = " ",
                Module        = " ",
                Namespace     = "󰦮 ",
                Null          = " ",
                Number        = "󰎠 ",
                Object        = " ",
                Operator      = " ",
                Package       = " ",
                Property      = " ",
                Reference     = " ",
                Snippet       = " ",
                String        = " ",
                Struct        = " ",
                TabNine       = "󰏚 ",
                Text          = " ",
                TypeParameter = " ",
                Unit          = " ",
                Value         = " ",
                Variable      = " ",
            },
            filter_kind = false,
        })
    end
}
